<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-H8U33OQ" failures="14" tests="81" name="testrunner.Runner" time="49.032" errors="0" timestamp="2023-07-26T16:46:59 CDT" skipped="0">
  <testcase classname="testrunner.Runner" name="runScenario" time="0.483"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.504">
    <failure message="expected [200] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.SubmitStepDef.user_receives_ok_status_with_response_body_for_submission(SubmitStepDef.java:124)
at ✽.User receives 200 OK Status with response body for submission.(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/5_Submit.feature:100)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.581"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.522"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.305"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.530"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.301">
    <failure message="expected [400] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.SubmitStepDef.user_receives_not_found_status_with_message_and_boolean_success_details_for_submission(SubmitStepDef.java:141)
at ✽.User receives 404 Not Found Status with message and boolean success details for submission(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/5_Submit.feature:89)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.519"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.309">
    <failure message="expected [200] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.SubmitStepDef.user_receives_ok_status_with_response_body_for_submission(SubmitStepDef.java:124)
at ✽.User receives 200 OK Status with response body for submission.(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/5_Submit.feature:84)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.583"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.312"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.539">
    <failure message="expected [404] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [400]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.SubmitStepDef.user_receives_bad_request_status_with_message_and_boolean_success_details_for_submit(SubmitStepDef.java:88)
at ✽.User receives 400 Bad Request Status with message and boolean success details for submit(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/5_Submit.feature:110)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.284"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.305"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.542"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.479"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.575">
    <failure message="expected [500] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [500] but found [400]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.ProgramStepDef.user_receives_bad_request_status_with_message_and_boolean_success_details_for_program(ProgramStepDef.java:215)
at ✽.User receives 400 Bad Request Status with message and boolean success details for program(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/1_Program.feature:86)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.293"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.338"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.622"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.521"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.362">
    <failure message="expected [500] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [500] but found [400]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.ProgramStepDef.user_receives_bad_request_status_with_message_and_boolean_success_details_for_program(ProgramStepDef.java:215)
at ✽.User receives 400 Bad Request Status with message and boolean success details for program(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/1_Program.feature:66)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.416"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="1.067"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.578">
    <failure message="expected [200] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.UserStepDef.user_receives_ok_status_with_user_details_response_body(UserStepDef.java:46)
at ✽.User receives 200 OK Status with user details response body.(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/3_User.feature:64)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.521">
    <failure message="expected [500] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [500] but found [400]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.ProgramStepDef.user_receives_bad_request_status_with_message_and_boolean_success_details_for_program(ProgramStepDef.java:215)
at ✽.User receives 400 Bad Request Status with message and boolean success details for program(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/1_Program.feature:76)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.586"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.304"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.405"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.339"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="6.283"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.311"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.496"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.378"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.521"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.379"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="2.823"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.493"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.796"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.507"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.533"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.304"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.325"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.291"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.529">
    <failure message="expected [200] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.DeleteStepDef.user_receives_ok_status_with_response_body_for_delete_submission(DeleteStepDef.java:37)
at ✽.User receives 200 OK Status with response body for delete submission.(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/6_Deletion.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.305"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.648"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.339"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.348"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.518">
    <failure message="expected [200] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.UserStepDef.user_receives_ok_status_with_user_details_response_body(UserStepDef.java:46)
at ✽.User receives 200 OK Status with user details response body.(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/3_User.feature:35)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.376"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.438">
    <failure message="expected [200] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.SubmitStepDef.user_receives_ok_status_with_response_body_for_submission(SubmitStepDef.java:124)
at ✽.User receives 200 OK Status with response body for submission.(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/5_Submit.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.569"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.769"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.541"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.380"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.305"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.727"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.316"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.595"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.775"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="2.093"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.555"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.539"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.403"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.499">
    <failure message="expected [200] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.SubmitStepDef.user_receives_not_found_status_with_message_and_boolean_success_details_for_submission(SubmitStepDef.java:141)
at ✽.User receives 404 Not Found Status with message and boolean success details for submission(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/5_Submit.feature:67)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.398">
    <failure message="expected [400] but found [404]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at stepdefinition.ProgramStepDef.user_receives_not_found_status_with_message_and_boolean_success_details_for_program(ProgramStepDef.java:175)
at ✽.User receives 404 Not Found Status with message and boolean success details for program(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/1_Program.feature:56)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.348"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.538"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.564"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.582"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.738"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.415"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.571">
    <failure message="1 expectation failed.
Expected status code &lt;201&gt; but was &lt;400&gt;.
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <400>.

at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at stepdefinition.SubmitStepDef.user_receives_created_status_with_success_submit_response_body(SubmitStepDef.java:59)
at ✽.User receives 201 Created Status with success submit response body.(file:///C:/Users/Shoban/eclipse-workspace/RestAssuredAPITesting/src/test/resources/Features/5_Submit.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.530"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.563"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.644"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.527"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.754"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.500"/>
  <system-out/>
  <testcase classname="testrunner.Runner" name="runScenario" time="0.328"/>
  <system-out/>
</testsuite> <!-- testrunner.Runner -->
